apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson1-4
  labels:
    app: goweb
spec:
  containers:
  - name: web
    image: mathinaction/lesson2:v0.2

    ports:
      - name: web
        containerPort: 8080
        protocol: TCP